apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invoice-app
  name: invoice-deployment
  namespace: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
      - name: invoiceapp
        image: invoiceapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
          name: http-web-svc