apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logistics-app
  name: logistics-deployment
  namespace: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics-app
  template:
    metadata:
      labels:
        app: logistics-app
    spec:
      containers:
      - name: logisticsapp
        image: logisticsapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
          name: http-web-svc