apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logistics-app
  name: logistics-deployment
  namespace: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics-app
  template:
    metadata:
      labels:
        app: logistics-app
    spec:
      dnsPolicy: Default 
      enableServiceLinks: false
      hostNetwork: false  
      hostPID: false
      hostIPC: false        
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000         
      containers:
      - name: logisticsapp
        image: logisticsapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
          name: http-web-svc
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
