apiVersion: v1
kind: Service
metadata:
  labels:
    app: logistics-app
  name: logistics-service
  namespace: shipping
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: logistics-app
  type: LoadBalancer