apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipping-app
  name: shipping-service
  namespace: shipping
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: shipping-app
  type: LoadBalancer
