apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-app
  name: order-deployment
  namespace: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      dnsPolicy: Default 
      enableServiceLinks: false
      hostNetwork: false  
      hostPID: false
      hostIPC: false        
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000         
      containers:
      - name: orderapp
        image: orderapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
          name: http-web-svc
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
