apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-app
  name: order-service
  namespace: order
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: order-app
  type: LoadBalancer
